export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_ALLORDERS_REQUEST = "GET_ALLORDERS_REQUEST";
export const GET_ALLORDERS_SUCCESS = "GET_ALLORDERS_SUCCESS";
export const GET_ALLORDERS_FAIL = "GET_ALLORDERS_FAIL";
